# Generated by Django 5.0 on 2024-04-17 14:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruit_shop_app', '0003_alter_productimage_image_alter_user_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag Table',
                'verbose_name_plural': 'Tags Table',
                'db_table': 'Tags',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Title of blog', max_length=100)),
                ('subtitle', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(null=True)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='blogs', to='fruit_shop_app.category')),
                ('tags', models.ManyToManyField(related_name='blogs', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog Table',
                'verbose_name_plural': 'Blogs Table',
                'db_table': 'Blogs',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default/default_blog.png', upload_to='images/blog_images/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Blog Image Table',
                'verbose_name_plural': 'Blog Images Table',
                'db_table': 'BlogImages',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
