# Generated by Django 5.0 on 2024-05-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default/default_fruit.jpg', max_length=1000, upload_to='images/product_images/'),
        ),
    ]
