# Generated by Django 5.0 on 2024-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', to='fruit_shop_app.product'),
        ),
    ]
