# Generated by Django 5.0 on 2024-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
