# Generated by Django 5.0 on 2024-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
        migrations.AlterField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(choices=[('all_products', 'All Products'), ('category', 'Category'), ('brand', 'Brand'), ('order', 'Order')], default='all_products', max_length=20),
        ),
    ]
