# Generated by Django 5.0 on 2024-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('set', 'Set'), ('pack', 'Pack'), ('unit', 'Unit')], default='unit'),
        ),
    ]
