# Generated by Django 5.0 on 2024-05-16 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 0, 21, 3, 439564, tzinfo=datetime.timezone.utc)),
        ),
    ]
