# Generated by Django 5.0 on 2024-05-16 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 2, 30, 41, 326712, tzinfo=datetime.timezone.utc)),
        ),
    ]
