# Generated by Django 5.0 on 2024-04-23 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_alter_address_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='amount_of_use',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='max_value_discount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='min_purchase_amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(choices=[('all_products', 'All Products'), ('category', 'Category'), ('specific_products', 'Specific Products')], default='all_products', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruit_shop_app.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='discount',
            name='minimum_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
