# Generated by Django 5.0 on 2024-05-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_remove_discount_products_alter_discount_applies_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruit_shop_app.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(choices=[('all_products', 'All Products'), ('category', 'Category'), ('brand', 'Brand')], default='all_products', max_length=20),
        ),
    ]
