# Generated by Django 5.0 on 2024-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_remove_user_full_name_remove_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
