# Generated by Django 5.0 on 2024-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_discount_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(choices=[('all_products', 'All Products'), ('category', 'Category'), ('specific_products', 'Specific Products'), ('brand', 'Brand')], default='all_products', max_length=20),
        ),
    ]
