# Generated by Django 5.0 on 2024-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default-avatar.png', upload_to='images/user_images'),
        ),
    ]
