# Generated by Django 5.0 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default/default_fruit.jpg', upload_to='images/product_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default/default_avatar.png', upload_to='images/user_images'),
        ),
        migrations.DeleteModel(
            name='CreateProductPermission',
        ),
    ]
