# Generated by Django 5.0 on 2024-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_alter_websiteimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteimage',
            name='image_type',
            field=models.CharField(choices=[('instagram', 'Instagram Image'), ('slide', 'Slide Image'), ('category', 'Category Image'), ('about', 'About Image')], help_text='Slide:(1342*932); Category:(354*354); About:(540*472)', max_length=20),
        ),
    ]
