# Generated by Django 5.0 on 2024-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0002_address_receiver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='commune',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
