# Generated by Django 5.0 on 2024-05-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0003_remove_orderitem_discount_applied_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='applies_to',
            field=models.CharField(blank=True, choices=[('all_products', 'All Products'), ('category', 'Category'), ('brand', 'Brand')], max_length=20, null=True),
        ),
    ]
