# Generated by Django 5.0 on 2024-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0003_remove_address_city_remove_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
    ]
