# Generated by Django 5.0 on 2024-05-16 09:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0003_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='fruit_shop_app.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='fruit_shop_app.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 9, 42, 22, 330927, tzinfo=datetime.timezone.utc)),
        ),
    ]
