# Generated by Django 5.0 on 2024-04-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0004_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='is_active',
        ),
    ]
