# Generated by Django 5.0 on 2024-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0004_alter_discount_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='fruit_shop_app.product'),
        ),
    ]
