# Generated by Django 5.0 on 2024-03-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0005_address_default_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default='', max_length=100),
        ),
    ]
