# Generated by Django 5.0 on 2024-04-14 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0006_remove_address_customer_remove_address_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount_of_use',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_discount', 'Fixed Discount')], default='percentage'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_value_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
