# Generated by Django 5.0 on 2024-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop_app', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('employee', 'Employee'), ('inventory_manager', 'Inventory Manager'), ('sales_associate', 'Sales Associate'), ('cashier', 'Cashier'), ('store_manager', 'Store Manager'), ('assistant_manager', 'Assistant Manager'), ('delivery_driver', 'Delivery Driver'), ('produce_specialist', 'Produce Specialist'), ('customer_service_representative', 'Customer Service Representative')], default='employee', max_length=200),
        ),
    ]
